using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

public partial class AcademicMaster : System.Web.UI.MasterPage
{
    private int _UserTypeID { get; set; } 
    int InchargeID = -1;
    protected void Page_Load(object sender, EventArgs e)
    {
     
        if (Session["EmailId"] == null)
        {
            Response.Redirect("Default.aspx");
        }
        else
        {
            lblUser.Text = Session["EmailId"].ToString();
            InchargeID = Convert.ToInt32(Session["InchargeID"].ToString());
            _UserTypeID = int.Parse(Session["UserTypeID"].ToString());
        }
        DataSet dsUser = new DataSet();
        dsUser = DAL.DalAccessUtility.GetDataInDataSet("exec USP_UserCount '" + InchargeID + "'");
        lblUserName.Text = dsUser.Tables[0].Rows[0]["InName"].ToString();
        lblMsg.Text = dsUser.Tables[5].Rows[0]["Msgco"].ToString();
        LoadLinks();
        AutoGeneratedCompliantsReport();
    }
    protected void lbLogOut_Click(object sender, EventArgs e)
    {
        Session.Abandon();
        Session.Clear();
        Response.Redirect("~/Default.aspx");
    }
    private void LoadLinks()
    {
        if (_UserTypeID == (int)TypeEnum.UserType.COMPLAINT || _UserTypeID == (int)TypeEnum.UserType.ACADEMIC)
        {
            liBillStatus.Visible = false;
            liComplaints.Visible = true;
            liDispatchStatusForLocal.Visible = false;
            liEstimate.Visible = false;
            liGallary.Visible = false;
            liViewMaterial.Visible = false;
            liWork.Visible = false;
            liStock.Visible = false;
            LiReject.Visible = false;
        }
    }

    public void SendAutoGeneratedComplaintsReport()
    {
        string msg = "Attached are the Pending Compliants Tickets on which no action has been taken.";
        string FileName = string.Empty;
        DataTable PendingCompliants = new DataTable();

        DateTime date = DateTime.Now.AddDays(-3);
        PendingCompliants = DAL.DalAccessUtility.GetDataInDataSet("exec AutoGeneratePendingCompliantReport'" + date + "'").Tables[0];

        System.Data.DataSet dsDegisDetails = new System.Data.DataSet();
        dsDegisDetails = DAL.DalAccessUtility.GetDataInDataSet("SELECT DISTINCT Incharge.LoginId FROM AcademyAssignToEmployee INNER JOIN Incharge ON AcademyAssignToEmployee.EmpId = Incharge.InchargeId  where AcademyAssignToEmployee.Active=1 and  Incharge.InchargeID='" + InchargeID + "' and Incharge.UserTypeId='" + (int)TypeEnum.UserType.COMPLAINT + "'");

        if (PendingCompliants != null)
        {
            FileName = "PendingCompliants" + "_" + DateTime.Now.Day + DateTime.Now.Month + DateTime.Now.Year + ".xls";
            string FilePath = Server.MapPath("Bills") + "\\" + FileName;

            PendingCompliants.TableName = FileName;
            PendingCompliants.WriteXml(FilePath);

            string to = dsDegisDetails.Tables[0].Rows[0]["LoginId"].ToString();
            string cc = string.Empty;
            try
            {
              //  Utility.SendEmailUsingAttachments(FilePath, to, cc, msg, "Pending Compliants");
            }
            catch { }
            finally
            {

            }
        }
    }

    public void AutoGeneratedCompliantsReport()
    {
        string FileName = string.Empty;

        FileName = "PendingCompliants" + "_" + DateTime.Now.Day + DateTime.Now.Month + DateTime.Now.Year + ".xls";
        string FilePath = Server.MapPath("Bills") + "\\" + FileName;
        if (!System.IO.File.Exists(FilePath))
        {
            SendAutoGeneratedComplaintsReport();
        }
    }
}