using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Net.Mail;
using System.IO;
using System.Net;
using System.Drawing;

public partial class Purchase_Home : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {

            if (Session["EmailId"] == null)
            {
                Response.Redirect("Default.aspx");
            }
            else
            {
                lblUser.Text = Session["EmailId"].ToString();
                hbnInchargeID.Value = Session["InchargeID"].ToString();
            }

            BindAllZoneDetails();
            AutoGeneratedPendencyReport();
        }
    }
    protected void BindAllZoneDetails()
    {
        DataSet dsZoneDetails = new DataSet();
        dsZoneDetails = DAL.DalAccessUtility.GetDataInDataSet("exec USP_ShowAllZoneDetails");
        DataTable dseEmp = new DataTable();
        dseEmp = DAL.DalAccessUtility.GetDataInDataSet("exec USP_LocationEmployee " + (int)TypeEnum.Module.Purchase).Tables[0];
        divZone.InnerHtml = string.Empty;
        string ZoneInfo = string.Empty;
        ZoneInfo += "<table class='table table-bordered table-striped table-condensed'>";
        ZoneInfo += "<thead>";
        ZoneInfo += "<tr>";
        ZoneInfo += "<th width='10%'>Zone Code</th>";
        ZoneInfo += "<th width='20%'>Zone Name</th>";
        ZoneInfo += "<th width='35%'>Location</th>";
        ZoneInfo += "<th width='25%'>Zone Incharge</th>";
        ZoneInfo += "<th width='10%'>Total Nos. of Academy</th>";
        ZoneInfo += "</tr>";
        ZoneInfo += "</thead>";
        ZoneInfo += "<tbody>";
        for (int i = 0; i < dsZoneDetails.Tables[0].Rows.Count; i++)
        {
            ZoneInfo += "<tr>";
            ZoneInfo += "<td width='10%' class='center'>" + dsZoneDetails.Tables[0].Rows[i]["ZoId"].ToString() + "</td>";
            //Session["ZoneId"] = dsZoneDetails.Tables[0].Rows[i]["ZoneId"].ToString();
            ZoneInfo += "<td width='20%' class='center'><a href='Purchase_AcademiesDetails.aspx?ZoneId=" + dsZoneDetails.Tables[0].Rows[i]["ZoneId"].ToString() + "'>" + dsZoneDetails.Tables[0].Rows[i]["ZoneName"].ToString() + "</a></td>";
            ZoneInfo += "<td width='35%' class='center'>";
            ZoneInfo += "<table>";
            ZoneInfo += "<tr><td> <b>State:</b> " + dsZoneDetails.Tables[0].Rows[i]["StateName"].ToString() + " </td></tr>";
            ZoneInfo += "<tr><td> <b>City:</b> " + dsZoneDetails.Tables[0].Rows[i]["CityName"].ToString() + "(" + dsZoneDetails.Tables[0].Rows[i]["Pincode"].ToString() + ")</td></tr>";
            ZoneInfo += "</table>";
            ZoneInfo += "</td>";
            ZoneInfo += "<td class='center' width='25%'>";
            ZoneInfo += "<table>";

            DataRow[] dr = dseEmp.Select("ZoneID=" + dsZoneDetails.Tables[0].Rows[i]["ZoneID"].ToString());
            if (dr != null)
            {

                for (int j = 0; j < dr.Length; j++)
                {
                    ZoneInfo += "<tr><td><span  title=' Mobile: " + dr[j]["InMobile"].ToString() + " \n Department: " + dr[j]["department"].ToString() + " \n Designation: " + dr[j]["Designation"].ToString() + "\n'  href='#'> " + dr[j]["InName"].ToString() + " </span></td></tr>";
                }
            }
            else
            {
                //ZoneInfo += "<a class='btn btn-setting btn-round'  href='AdminHome.aspx?ZoneId=" + dsZoneDetails.Tables[0].Rows[i]["ZoneId"].ToString() + "'><span class='label label-important' style='font-size: 15.998px;'>Please Allot Incharge</span></a>";
                //Session["ZoneId"] = dsZoneDetails.Tables[0].Rows[i]["ZoneId"].ToString();
                ZoneInfo += "<a href='#'><span class='label label-important' style='font-size: 15.998px;'>Requst To Admin</span></a>";
                //DataSet dsZoneName = new DataSet();
                //dsZoneName = DAL.DalAccessUtility.GetDataInDataSet("select ZoneName from zone where ZoneId='" + Session["ZoneId"].ToString() + "'");
                //lblZone.Text = dsZoneName.Tables[0].Rows[i]["ZoneName"].ToString();
            }
            ZoneInfo += "</table>";
            ZoneInfo += "</td>";
            //Session["ZoneId"] = dsZoneDetails.Tables[0].Rows[i]["ZoneId"].ToString();
            //DataSet dsZoneName = new DataSet();
            //dsZoneName = DAL.DalAccessUtility.GetDataInDataSet("select ZoneName from zone where ZoneId='" + Session["ZoneId"].ToString() + "'");
            //lblZone.Text = dsZoneName.Tables[0].Rows[0]["ZoneName"].ToString();

            ZoneInfo += "<td width='10%' class='center'>" + dsZoneDetails.Tables[0].Rows[i]["Coun"].ToString() + "</td>";
            ZoneInfo += "</tr>";
        }
        ZoneInfo += "</tbody>";
        ZoneInfo += "</table>";
        divZone.InnerHtml = ZoneInfo.ToString();
        //lblZone.Text = dsZoneDetails.Tables[0].Rows[0]["ZoneName"].ToString();
    }



    public void SendAutoGeneratedPendencyReport()
    {
        string msg = "Attached is the auto generated report of more than 15 days pending estimates.";
        string FileName = string.Empty;
        int UserTypeID = Convert.ToInt16(Session["UserTypeID"].ToString());
        int UserID = Convert.ToInt32(Session["InchargeID"].ToString());
        DataTable PendingEst = new DataTable();
        DataSet ds = new DataSet();
        PendingEst = DAL.DalAccessUtility.GetDataInDataSet("exec [USP_PendingReportForPurchaser]" + (int)TypeEnum.PurchaseSourceID.Mohali).Tables[0];
        if (PendingEst != null)
        {
            FileName = "PendingReport" + "_" + DateTime.Now.Day + DateTime.Now.Month + DateTime.Now.Year + ".xls";

            string FilePath = Server.MapPath("EstFile") + "\\" + FileName;
            PendingEst.TableName = FileName;
            PendingEst.WriteXml(@FilePath);

            string to = "akalconstruction@barusahib.org,dsingh@barusahib.org,csmavi@gmail.com";
            string cc = "jagjit@barusahib.org";
            Utility.SendEmailUsingAttachments(@FilePath, to, cc, msg, "Pending Estimates");
        }
    }


    public void AutoGeneratedPendencyReport()
    {
        AutogeneratedEmail emaildays = new AutogeneratedEmail();
        PurchaseRepository repo = new PurchaseRepository(new AkalAcademy.DataContext());
        emaildays = repo.GetReportDay((int)TypeEnum.AutoGenerateReportType.PendingReport);
        string[] days = emaildays.DayOfMonth.Split(',');

        if ((DateTime.Now.Day == int.Parse(days[0]) || DateTime.Now.Day == int.Parse(days[1])) && emaildays.EmailSent == false)
        {
            emaildays.EmailSent = true;
            SendAutoGeneratedPendencyReport();
            repo.UpdateAutogeneratedEmail(emaildays);
        }
        else if ((DateTime.Now.Day == int.Parse(days[0]) || DateTime.Now.Day == int.Parse(days[1])) && emaildays.EmailSent == true)
        {
            emaildays.EmailSent = true;
            repo.UpdateAutogeneratedEmail(emaildays);
        }
        else
        {
            emaildays.EmailSent = false;
            repo.UpdateAutogeneratedEmail(emaildays);
        }
    }
}