using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class RateApproved : System.Web.UI.Page
{
    private int InchargeID { get; set; }
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["EmailId"] == null)
        {
            Response.Redirect("Default.aspx");
        }
        else
        {
            lblUser.Text = Session["EmailId"].ToString();
            InchargeID = Convert.ToInt32(Session["InchargeID"].ToString());
        }
        if (!IsPostBack)
        {
            BindNonApprovedRateMaterial();
        }

      
    }

    protected void BindNonApprovedRateMaterial()
    {
        DataSet dsMat = new DataSet();
        dsMat = DAL.DalAccessUtility.GetDataInDataSet("Select M.MatId,MT.MatTypeName,M.MatName,M.MatCost,U.UnitName,MN.Rate,Inc.InName,MN.CreatedOn from Material M INNER JOIN MaterialNonApprovedRate MN on M.MatId = MN.MatID INNER JOIN MaterialType MT on M.MatTypeId = MT.MatTypeId INNER JOIN Unit U On M.UnitId = U.UnitId INNER JOIN Incharge Inc On MN.CreatedBy = Inc.InchargeId");
        grvNonApprovedRateDetails.DataSource = dsMat;
        grvNonApprovedRateDetails.DataBind();
    }
    protected void btn_Approved_Click(object sender, EventArgs e)
    {

        MaterialRateApproved materialrateapproved = new MaterialRateApproved();
        GridViewRow gr = (GridViewRow)((DataControlFieldCell)((Button)sender).Parent).Parent;

        Button btnapproved = (Button)gr.FindControl("btn_Approved");
        Label txtRate = (Label)gr.FindControl("txtRate");
        TextBox txtNewRate = (TextBox)gr.FindControl("txtNewRate");

        string approvedid = btnapproved.CommandArgument.ToString();

        DAL.DalAccessUtility.ExecuteNonQuery("Update Material set MatCost='" + txtNewRate.Text + "',IsRateApproved = 1 where MatId = '" + approvedid + "'");
        DataTable dsNonMat = DAL.DalAccessUtility.GetDataInDataSet("Select MN.CreatedBy,inc.LoginId FROM  MaterialNonApprovedRate MN INNER JOIN Incharge Inc ON MN.CreatedBy = Inc.InchargeId WHERE MN.MatId= '" + approvedid + "'").Tables[0];
  
        materialrateapproved.MatID = Convert.ToInt32(approvedid);
        materialrateapproved.ApprovedRate = Convert.ToDecimal(txtNewRate.Text);
        materialrateapproved.ApprovedBy = InchargeID;
        materialrateapproved.ApprovedOn = Utility.GetLocalDateTime(DateTime.UtcNow);
        materialrateapproved.RequestedBy = Convert.ToInt32(dsNonMat.Rows[0]["CreatedBy"].ToString());

        ConstructionUserRepository repo = new ConstructionUserRepository(new AkalAcademy.DataContext());
        repo.SaveApprovedMaterial(materialrateapproved);
        DataTable dsMat = DAL.DalAccessUtility.GetDataInDataSet("Select MatName from Material where MatId = '" + approvedid + "'").Tables[0];

        SendAutoGeneratedComplaintsReport(dsMat.Rows[0]["MatName"].ToString(), txtNewRate.Text, dsNonMat.Rows[0]["LoginId"].ToString());

        DAL.DalAccessUtility.ExecuteNonQuery("Delete from MaterialNonApprovedRate where MatId = '" + approvedid + "'");

        BindNonApprovedRateMaterial();
        ScriptManager.RegisterClientScriptBlock(this.Page, this.GetType(), "Startup", "<script>alert('Rate Approved Successfully');</script>", false);
    }

    public void SendAutoGeneratedComplaintsReport(string Material, string NewRate,string loginID)
    {
        string MsgInfo = string.Empty;
        MsgInfo += "<table style='width:100%;'>";
        MsgInfo += "<tr>";
        MsgInfo += "<td style='padding:0px; text-align:left; width:50%' valign='top'>";
        MsgInfo += "<img src='http://akalsewa.org/img/logoakalnew.png' style='width:100%;' />";
        MsgInfo += "</td>";
        MsgInfo += "<td style='text-align: right; width:40%;'>";
        MsgInfo += "<br /><br />";
        MsgInfo += "<div style='font-style:italic; text-align: right;'>";
        MsgInfo += "Baru Shahib,";
        MsgInfo += "<br />Dist: Sirmaur";
        MsgInfo += "<br />Himachal Pradesh-173001";
        MsgInfo += "</td>";
        MsgInfo += "</tr>";
        MsgInfo += "<tr>";
        MsgInfo += "<td colspan='2' style='height:50px'>";
        MsgInfo += "New Rate for Materials Approved By Purchase Committee.Please click on <a href='http://akalsewa.org/'>Akal Sewa</a>";
        MsgInfo += "</td>";
        MsgInfo += "</tr>";
        MsgInfo += "</table>";
        MsgInfo += "<table border='1' style='width:100%'>";
        MsgInfo += "<tbody>";
        MsgInfo += "<tr>";
        MsgInfo += "<td>";
        MsgInfo += "<b>Material Name:</b>";
        MsgInfo += "</td>";
        MsgInfo += "<td>";
        MsgInfo += Material;
        MsgInfo += "</td>";
        MsgInfo += "</tr>";
        MsgInfo += "<tr>";
        MsgInfo += "<td>";
        MsgInfo += "<b>New Rate:</b>";
        MsgInfo += "</td>";
        MsgInfo += "<td>";
        MsgInfo += NewRate;
        MsgInfo += "</td>";
        MsgInfo += "</tr>";
        MsgInfo += "</tbody>";
        MsgInfo += "</table>";
        string FileName = string.Empty;
        string to = "itmohali@barusahib.org";
        string cc = loginID;

        try
        {
          // Utility.SendEmailWithoutAttachments(to, cc, MsgInfo, "New Rate Approved Successfully.");
        }
        catch { }
        finally
        {

        }

    }
}