using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

/// <summary>
/// Summary description for AutogeneratedEmail
/// </summary>
public class AutogeneratedEmail
{
    public AutogeneratedEmail()
    {

    }
    [Key()]

    public int ID { get; set; }

    public int? EmailType { get; set; }

    public string DayOfMonth { get; set; }

    public bool? EmailSent { get; set; }
}