USE [Akal]
GO
/****** Object:  Table [dbo].[AutogeneratedEmail]    Script Date: 11/24/2016 4:36:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AutogeneratedEmail](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EmailType] [int] NULL,
	[DayOfMonth] [varchar](10) NULL,
	[EmailSent] [bit] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[EmailTemplates]    Script Date: 11/24/2016 4:36:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EmailTemplates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EmailTypeName] [varchar](50) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[AutogeneratedEmail] ON 

INSERT [dbo].[AutogeneratedEmail] ([ID], [EmailType], [DayOfMonth], [EmailSent]) VALUES (1, 1, N'15,30', 1)
SET IDENTITY_INSERT [dbo].[AutogeneratedEmail] OFF
SET IDENTITY_INSERT [dbo].[EmailTemplates] ON 

INSERT [dbo].[EmailTemplates] ([Id], [EmailTypeName]) VALUES (1, N'PendingReport')
SET IDENTITY_INSERT [dbo].[EmailTemplates] OFF
