
insert into city values(31,16,'Birmingham',0,1,null,'ADMIN',NULL,NULL)
insert into city values(31,16,'Birmingham',0,1,null,'ADMIN',NULL,NULL)
insert into city values(31,16,'Montgomery',0,1,null,'ADMIN',NULL,NULL)
insert into city values(31,16,'Mobile',0,1,null,'ADMIN',NULL,NULL)
insert into city values(31,16,'Huntsville',0,1,null,'ADMIN',NULL,NULL)

insert into city values(32,16,'Anchorage',0,1,null,'ADMIN',NULL,NULL)

insert into city values(33,16,'Phoenix',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Tucson',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Mesa',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Chandler',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Gilbert',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Glendale',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Scottsdale',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Tempe',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Peoria',0,1,null,'ADMIN',NULL,NULL)
insert into city values(33,16,'Surprise',0,1,null,'ADMIN',NULL,NULL)

insert into city values(34,16,'Little Rock',0,1,null,'ADMIN',NULL,NULL)


insert into city values(35,16,'Los Angeles',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'San Diego',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'San Jose',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'San Francisco',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Fresno',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Sacramento',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Long Beach',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Oakland',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Bakersfield	',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Anaheim',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Santa Ana',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Riverside',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Stockton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Chula Vista',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Irvine',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	San Bernardino',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Modesto',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Oxnard',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Fontana',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Moreno Valley',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Huntington Beach',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Glendale',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Santa Clarita',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Garden Grove',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Oceanside',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Rancho Cucamonga',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Santa Rosa',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Ontario',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Elk Grove',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Corona',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Lancaster',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Palmdale',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Salinas',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Hayward',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Pomona',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Escondido',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Sunnyvale',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Torrance',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Pasadena',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Orange',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Fullerton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Thousand Oaks',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Visalia	',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Roseville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Concord	',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Simi Valley',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Santa Clara',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Victorville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Vallejo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Berkeley',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'El Monte',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Downey	',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Costa Mesa',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Carlsbad',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Fairfield',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Ventura',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Temecula',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Antioch',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Richmond',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	West Covina',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Murrieta',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Norwalk',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Daly City',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Burbank',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	Santa Maria',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'El Cajon',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'	San Mateo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Rialto',0,1,null,'ADMIN',NULL,NULL)
insert into city values(35,16,'Clovis',0,1,null,'ADMIN',NULL,NULL)


insert into city values(36,16,'Denver',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Colorado Springs',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Aurora',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Fort Collins',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Lakewood',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Thornton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Arvada',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Westminster	Colorado',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Pueblo	Colorado',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Centennial	Colorado',0,1,null,'ADMIN',NULL,NULL)
insert into city values(36,16,'Boulder	Colorado',0,1,null,'ADMIN',NULL,NULL)


insert into city values(37,16,'Bridgeport',0,1,null,'ADMIN',NULL,NULL)
insert into city values(37,16,'New Haven',0,1,null,'ADMIN',NULL,NULL)
insert into city values(37,16,'Stamford',0,1,null,'ADMIN',NULL,NULL)
insert into city values(37,16,'Hartford',0,1,null,'ADMIN',NULL,NULL)
insert into city values(37,16,'Waterbury',0,1,null,'ADMIN',NULL,NULL)

insert into city values(39,16,'Washington',0,1,null,'ADMIN',NULL,NULL)


insert into city values(40,16,'Jacksonville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Miami',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Tampa',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Orlando',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'St. Petersburg',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Hialeah',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Tallahassee',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Fort Lauderdale',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Port St. Lucie',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Cape Coral',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Pembroke Pines',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'	Hollywood',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Miramar',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Gainesville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Coral Springs',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Miami Gardens',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Clearwater',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'	Pompano Beach',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Palm Bay',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'West Palm Beach',0,1,null,'ADMIN',NULL,NULL)
insert into city values(40,16,'Lakeland',0,1,null,'ADMIN',NULL,NULL)

insert into city values(41,16,'Atlanta',0,1,null,'ADMIN',NULL,NULL)
insert into city values(41,16,'Columbus',0,1,null,'ADMIN',NULL,NULL)
insert into city values(41,16,'Augusta',0,1,null,'ADMIN',NULL,NULL)
insert into city values(41,16,'Macon',0,1,null,'ADMIN',NULL,NULL)
insert into city values(41,16,'Savannah',0,1,null,'ADMIN',NULL,NULL)
insert into city values(41,16,'Athens',0,1,null,'ADMIN',NULL,NULL)
insert into city values(41,16,'Sandy Springs',0,1,null,'ADMIN',NULL,NULL)

insert into city values(42,16,'Honolulu',0,1,null,'ADMIN',NULL,NULL)

insert into city values(43,16,'Boise',0,1,null,'ADMIN',NULL,NULL)

insert into city values(44,16,'Chicago',0,1,null,'ADMIN',NULL,NULL)
insert into city values(44,16,'Aurora',0,1,null,'ADMIN',NULL,NULL)
insert into city values(44,16,'Rockford',0,1,null,'ADMIN',NULL,NULL)
insert into city values(44,16,'Jolie',0,1,null,'ADMIN',NULL,NULL)
insert into city values(44,16,'Naperville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(44,16,'Springfield',0,1,null,'ADMIN',NULL,NULL)
insert into city values(44,16,'Peoria',0,1,null,'ADMIN',NULL,NULL)
insert into city values(44,16,'Elgin',0,1,null,'ADMIN',NULL,NULL)

insert into city values(45,16,'Indianapolis',0,1,null,'ADMIN',NULL,NULL)
insert into city values(45,16,'Fort Wayne',0,1,null,'ADMIN',NULL,NULL)
insert into city values(45,16,'Evansville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(45,16,'South Bend',0,1,null,'ADMIN',NULL,NULL)

insert into city values(46,16,'Des Moines',0,1,null,'ADMIN',NULL,NULL)
insert into city values(46,16,'Cedar Rapids',0,1,null,'ADMIN',NULL,NULL)
insert into city values(46,16,'Davenport',0,1,null,'ADMIN',NULL,NULL)

insert into city values(47,16,'Wichita',0,1,null,'ADMIN',NULL,NULL)
insert into city values(47,16,'Overland Park',0,1,null,'ADMIN',NULL,NULL)
insert into city values(47,16,'Kansas City',0,1,null,'ADMIN',NULL,NULL)
insert into city values(47,16,'Olathe',0,1,null,'ADMIN',NULL,NULL)
insert into city values(47,16,'Topeka',0,1,null,'ADMIN',NULL,NULL)

insert into city values(48,16,'Louisville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(48,16,'Lexington',0,1,null,'ADMIN',NULL,NULL)

insert into city values(49,16,'New Orleans',0,1,null,'ADMIN',NULL,NULL)
insert into city values(49,16,'Baton Rouge',0,1,null,'ADMIN',NULL,NULL)
insert into city values(49,16,'Shreveport',0,1,null,'ADMIN',NULL,NULL)
insert into city values(49,16,'Lafayette',0,1,null,'ADMIN',NULL,NULL)

insert into city values(50,16,'Baltimore',0,1,null,'ADMIN',NULL,NULL)

insert into city values(51,16,'Boston',0,1,null,'ADMIN',NULL,NULL)
insert into city values(51,16,'Worcester',0,1,null,'ADMIN',NULL,NULL)
insert into city values(51,16,'Springfield',0,1,null,'ADMIN',NULL,NULL)
insert into city values(51,16,'Lowell',0,1,null,'ADMIN',NULL,NULL)
insert into city values(51,16,'Cambridge',0,1,null,'ADMIN',NULL,NULL)

insert into city values(52,16,'Detroit',0,1,null,'ADMIN',NULL,NULL)
insert into city values(52,16,'Grand Rapids',0,1,null,'ADMIN',NULL,NULL)
insert into city values(52,16,'Warren',0,1,null,'ADMIN',NULL,NULL)
insert into city values(52,16,'Sterling Heights',0,1,null,'ADMIN',NULL,NULL)
insert into city values(52,16,'Ann Arbor',0,1,null,'ADMIN',NULL,NULL)
insert into city values(52,16,'Lansing',0,1,null,'ADMIN',NULL,NULL)

insert into city values(53,16,'Minneapolis',0,1,null,'ADMIN',NULL,NULL)
insert into city values(53,16,'Saint Paul',0,1,null,'ADMIN',NULL,NULL)
insert into city values(53,16,'	Rochester',0,1,null,'ADMIN',NULL,NULL)

insert into city values(54,16,'Jackson',0,1,null,'ADMIN',NULL,NULL)

insert into city values(55,16,'Kansas City',0,1,null,'ADMIN',NULL,NULL)
insert into city values(55,16,'St. Louis',0,1,null,'ADMIN',NULL,NULL)
insert into city values(55,16,'Springfield',0,1,null,'ADMIN',NULL,NULL)
insert into city values(55,16,'Independence',0,1,null,'ADMIN',NULL,NULL)
insert into city values(55,16,'	Columbia',0,1,null,'ADMIN',NULL,NULL)

insert into city values(56,16,'Billings',0,1,null,'ADMIN',NULL,NULL)

insert into city values(57,16,'Omaha',0,1,null,'ADMIN',NULL,NULL)
insert into city values(57,16,'Lincoln	',0,1,null,'ADMIN',NULL,NULL)

insert into city values(58,16,'Las Vegas',0,1,null,'ADMIN',NULL,NULL)
insert into city values(58,16,'Henderson',0,1,null,'ADMIN',NULL,NULL)
insert into city values(58,16,'Reno',0,1,null,'ADMIN',NULL,NULL)
insert into city values(58,16,'North Las Vegas',0,1,null,'ADMIN',NULL,NULL)

insert into city values(59,16,'Manchester',0,1,null,'ADMIN',NULL,NULL)

insert into city values(60,16,'Newark',0,1,null,'ADMIN',NULL,NULL)
insert into city values(60,16,'Jersey City',0,1,null,'ADMIN',NULL,NULL)
insert into city values(60,16,'Paterson',0,1,null,'ADMIN',NULL,NULL)
insert into city values(60,16,'Elizabeth',0,1,null,'ADMIN',NULL,NULL)
insert into city values(60,16,'Edison',0,1,null,'ADMIN',NULL,NULL)
insert into city values(60,16,'Woodbridge',0,1,null,'ADMIN',NULL,NULL)

insert into city values(61,16,'Albuquerque',0,1,null,'ADMIN',NULL,NULL)
insert into city values(61,16,'Las Cruces',0,1,null,'ADMIN',NULL,NULL)

insert into city values(62,16,'New York',0,1,null,'ADMIN',NULL,NULL)
insert into city values(62,16,'Buffalo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(62,16,'Rochester',0,1,null,'ADMIN',NULL,NULL)
insert into city values(62,16,'Yonkers',0,1,null,'ADMIN',NULL,NULL)
insert into city values(62,16,'Syracuse',0,1,null,'ADMIN',NULL,NULL)

insert into city values(63,16,'Charlotte',0,1,null,'ADMIN',NULL,NULL)
insert into city values(63,16,'Raleigh',0,1,null,'ADMIN',NULL,NULL)
insert into city values(63,16,'Greensboro',0,1,null,'ADMIN',NULL,NULL)
insert into city values(63,16,'Durham',0,1,null,'ADMIN',NULL,NULL)
insert into city values(63,16,'Winston–Salem',0,1,null,'ADMIN',NULL,NULL)
insert into city values(63,16,'Fayetteville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(63,16,'Cary',0,1,null,'ADMIN',NULL,NULL)
insert into city values(63,16,'Wilmington',0,1,null,'ADMIN',NULL,NULL)
insert into city values(63,16,'High Point',0,1,null,'ADMIN',NULL,NULL)

insert into city values(64,16,'Fargo',0,1,null,'ADMIN',NULL,NULL)

insert into city values(65,16,'Columbus',0,1,null,'ADMIN',NULL,NULL)
insert into city values(65,16,'Cleveland',0,1,null,'ADMIN',NULL,NULL)
insert into city values(65,16,'Cincinnati',0,1,null,'ADMIN',NULL,NULL)
insert into city values(65,16,'Toledo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(65,16,'Akron',0,1,null,'ADMIN',NULL,NULL)
insert into city values(65,16,'	Dayton',0,1,null,'ADMIN',NULL,NULL)


insert into city values(66,16,'Oklahoma City',0,1,null,'ADMIN',NULL,NULL)
insert into city values(66,16,'Tulsa',0,1,null,'ADMIN',NULL,NULL)
insert into city values(66,16,'Norman',0,1,null,'ADMIN',NULL,NULL)
insert into city values(66,16,'Broken Arrow',0,1,null,'ADMIN',NULL,NULL)

insert into city values(67,16,'Portland',0,1,null,'ADMIN',NULL,NULL)
insert into city values(67,16,'Salem',0,1,null,'ADMIN',NULL,NULL)
insert into city values(67,16,'Eugene',0,1,null,'ADMIN',NULL,NULL)
insert into city values(67,16,'Gresham',0,1,null,'ADMIN',NULL,NULL)

insert into city values(68,16,'Philadelphia',0,1,null,'ADMIN',NULL,NULL)
insert into city values(68,16,'Pittsburgh',0,1,null,'ADMIN',NULL,NULL)
insert into city values(68,16,'Allentown',0,1,null,'ADMIN',NULL,NULL)

insert into city values(69,16,'Providence',0,1,null,'ADMIN',NULL,NULL)

insert into city values(70,16,'Columbia',0,1,null,'ADMIN',NULL,NULL)
insert into city values(70,16,'Charleston',0,1,null,'ADMIN',NULL,NULL)
insert into city values(70,16,'North Charleston',0,1,null,'ADMIN',NULL,NULL)

insert into city values(71,16,'Sioux Falls',0,1,null,'ADMIN',NULL,NULL)

insert into city values(72,16,'Memphis',0,1,null,'ADMIN',NULL,NULL)
insert into city values(72,16,'Nashville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(72,16,'Knoxville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(72,16,'Chattanooga',0,1,null,'ADMIN',NULL,NULL)
insert into city values(72,16,'Clarksville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(72,16,'	Murfreesboro',0,1,null,'ADMIN',NULL,NULL)

insert into city values(73,16,'Houston',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'San Antonio',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Dallas',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Austin',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Fort Worth',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'El Paso',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Arlington',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Corpus Christi',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Plano',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Laredo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Lubbock',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Garland	',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Irving',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Amarillo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Grand Prairie',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Brownsville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'McKinney',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Pasadena',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Frisco',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Mesquite',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'McAllen',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Killeen',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Waco',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Carrollton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Denton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Midland',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Abilene',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Beaumont',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Odessa',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Round Rock',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Richardson',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Wichita Falls',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'College Station',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Pearland',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Lewisville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(73,16,'Tyler',0,1,null,'ADMIN',NULL,NULL)

insert into city values(74,16,'Salt Lake City',0,1,null,'ADMIN',NULL,NULL)
insert into city values(74,16,'West Valley City',0,1,null,'ADMIN',NULL,NULL)
insert into city values(74,16,'Provo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(74,16,'West Jordan',0,1,null,'ADMIN',NULL,NULL)

insert into city values(75,16,'Virginia Beach',0,1,null,'ADMIN',NULL,NULL)
insert into city values(75,16,'Norfolk',0,1,null,'ADMIN',NULL,NULL)
insert into city values(75,16,'Chesapeake',0,1,null,'ADMIN',NULL,NULL)
insert into city values(75,16,'Richmond',0,1,null,'ADMIN',NULL,NULL)
insert into city values(75,16,'Newport News',0,1,null,'ADMIN',NULL,NULL)
insert into city values(75,16,'Alexandria',0,1,null,'ADMIN',NULL,NULL)
insert into city values(75,16,'Hampton',0,1,null,'ADMIN',NULL,NULL)

insert into city values(76,16,'Seattle',0,1,null,'ADMIN',NULL,NULL)
insert into city values(76,16,'Spokane',0,1,null,'ADMIN',NULL,NULL)
insert into city values(76,16,'Tacoma',0,1,null,'ADMIN',NULL,NULL)
insert into city values(76,16,'Vancouver',0,1,null,'ADMIN',NULL,NULL)
insert into city values(76,16,'Bellevue',0,1,null,'ADMIN',NULL,NULL)
insert into city values(76,16,'Kent',0,1,null,'ADMIN',NULL,NULL)
insert into city values(76,16,'Everett',0,1,null,'ADMIN',NULL,NULL)

insert into city values(77,16,'Milwaukee',0,1,null,'ADMIN',NULL,NULL)
insert into city values(77,16,'Madison',0,1,null,'ADMIN',NULL,NULL)
insert into city values(77,16,'Green Bay',0,1,null,'ADMIN',NULL,NULL)


--Canada

insert into city values(78,17,'Calgary',0,1,null,'ADMIN',NULL,NULL)
insert into city values(78,17,'Edmonton',0,1,null,'ADMIN',NULL,NULL)

insert into city values(79,17,'Abbotsford',0,1,null,'ADMIN',NULL,NULL)
insert into city values(79,17,'Prince George',0,1,null,'ADMIN',NULL,NULL)
insert into city values(79,17,'Surrey',0,1,null,'ADMIN',NULL,NULL)
insert into city values(79,17,'Kamloops',0,1,null,'ADMIN',NULL,NULL)


insert into city values(80,17,'Gillam',0,1,null,'ADMIN',NULL,NULL)
insert into city values(80,17,'Leaf Rapids',0,1,null,'ADMIN',NULL,NULL)
insert into city values(80,17,'Snow Lake',0,1,null,'ADMIN',NULL,NULL)
insert into city values(80,17,'Lynn Lake',0,1,null,'ADMIN',NULL,NULL)
insert into city values(80,17,'Winnipeg',0,1,null,'ADMIN',NULL,NULL)

insert into city values(81,17,'Saint John',0,1,null,'ADMIN',NULL,NULL)

insert into city values(82,17,'St. John',0,1,null,'ADMIN',NULL,NULL)
insert into city values(82,17,'Baie Verte',0,1,null,'ADMIN',NULL,NULL)
insert into city values(82,17,'Happy Valley-Goose Bay',0,1,null,'ADMIN',NULL,NULL)

insert into city values(86,17,'Greater Sudbury',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Kawartha Lakes',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Timmins',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Ottawa',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Norfolk County',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Haldimand County',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Hamilton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Prince Edward County',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Brant',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Elliot Lake',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Huntsville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Caledon',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Laurentian Hills',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Toronto',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Bracebridge',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Iroquois Falls',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Moosonee',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Cochrane',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'South Bruce Peninsula',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Kearney',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Lakeshore',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Blind River',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Mississippi Mills',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Gravenhurst',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Northeastern Manitoulin and the Islands',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Quinte West',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Greater Napanee',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Kingston',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'London',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Milton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Thunder Bay',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'North Bay',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Plympton-Wyoming',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Minto',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Clarence-Rockland',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Erin',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Mississauga',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Georgina',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'The Blue Mountains',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Innisfil',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Essex',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Mono',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Halton Hills',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'New Tecumseth',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Vaughan',0,1,null,'ADMIN',NULL,NULL)
insert into city values(86,17,'Brampton',0,1,null,'ADMIN',NULL,NULL)



insert into city values(88,17,'La Tuqu',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Senneterre',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Rouyn-Noranda',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Val-d',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Sept-Îles',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Saguenay',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Gaspé',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Port-Cartier',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Shawinigan',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Témiscaming',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Chibougamau',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Saint-Raymond',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Mont-Laurier',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Dégelis',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Belleterre',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Baie-Saint-Paul',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Mirabel',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Fermont',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'La Malbaie',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Rivière-Rouge',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Quebec City',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Lévis',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Bécancour',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Percé',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Amos',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Chandler',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Gracefield',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Montreal',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Saint-Félicien',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Sherbrooke',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Gatineau',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Pohénégamook',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Rimouski',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Baie-Comeau',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Cookshire-Eaton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Dolbeau-Mistassini',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Trois-Rivières',0,1,null,'ADMIN',NULL,NULL)
insert into city values(88,17,'Sainte-Anne-des-Monts',0,1,null,'ADMIN',NULL,NULL)

insert into city values(90,17,'Whitehorse',0,1,null,'ADMIN',NULL,NULL)

--Malayasia

insert into city values(127,18,'Johor Bahru Tengah',0,1,null,'ADMIN',NULL,NULL)
insert into city values(127,18,'Johor Bahru',0,1,null,'ADMIN',NULL,NULL)

insert into city values(128,18,'Alor Setar',0,1,null,'ADMIN',NULL,NULL)

insert into city values(130,18,'Melaka Bandaraya Bersejarah',0,1,null,'ADMIN',NULL,NULL)

insert into city values(132,18,'Penang',0,1,null,'ADMIN',NULL,NULL)

insert into city values(133,18,'Ipoh',0,1,null,'ADMIN',NULL,NULL)

insert into city values(140,18,'Kota Kinabalu',0,1,null,'ADMIN',NULL,NULL)

insert into city values(135,18,'Miri',0,1,null,'ADMIN',NULL,NULL)
insert into city values(135,18,'Kuching Utara',0,1,null,'ADMIN',NULL,NULL)
insert into city values(135,18,'Kuching Selatan',0,1,null,'ADMIN',NULL,NULL)

insert into city values(136,18,'Shah Alam',0,1,null,'ADMIN',NULL,NULL)
insert into city values(136,18,'Petaling Jaya',0,1,null,'ADMIN',NULL,NULL)

insert into city values(137,18,'Kuala Terengganu',0,1,null,'ADMIN',NULL,NULL)


--Aust

insert into city values(95,20,'Australian Capital Territory',0,1,null,'ADMIN',NULL,NULL)
insert into city values(95,20,'Canberra–Queanbeyan',0,1,null,'ADMIN',NULL,NULL)

insert into city values(96,20,'Sydney',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Newcastle–Maitland',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Wollongong',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Coffs Harbour',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Wagga Wagga',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Port Macquarie',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Tamworth',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Orange',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Bowral–Mittagong',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Dubbo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Bathurst',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Nowra–Bomaderry',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Gold Coast–Tweed Heads',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Albury–Wodonga',0,1,null,'ADMIN',NULL,NULL)
insert into city values(96,20,'Mildura–Wentworth',0,1,null,'ADMIN',NULL,NULL)

insert into city values(97,20,'Darwin',0,1,null,'ADMIN',NULL,NULL)


insert into city values(98,20,'Brisbane',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Sunshine Coast',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Townsville',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Cairns',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Toowoomba',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Mackay',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Rockhampton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Bundaberg',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Hervey Bay',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Gladstone–Tannum Sands',0,1,null,'ADMIN',NULL,NULL)
insert into city values(98,20,'Gold Coast–Tweed Heads',0,1,null,'ADMIN',NULL,NULL)

insert into city values(99,20,'Adelaide',0,1,null,'ADMIN',NULL,NULL)

insert into city values(100,20,'Hobart',0,1,null,'ADMIN',NULL,NULL)
insert into city values(100,20,'Launceston',0,1,null,'ADMIN',NULL,NULL)
insert into city values(100,20,'Devonport',0,1,null,'ADMIN',NULL,NULL)

insert into city values(101,20,'Melbourne',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Geelong',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Ballarat',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Bendigo',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Shepparton–Mooroopna',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Traralgon–Morwell',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Warrnambool',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Warragul–Drouin',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Albury–Wodonga',0,1,null,'ADMIN',NULL,NULL)
insert into city values(101,20,'Mildura–Wentworth',0,1,null,'ADMIN',NULL,NULL)


insert into city values(102,20,'Perth',0,1,null,'ADMIN',NULL,NULL)
insert into city values(102,20,'Bunbury',0,1,null,'ADMIN',NULL,NULL)
insert into city values(102,20,'Geraldton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(102,20,'Busselton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(102,20,'Albany',0,1,null,'ADMIN',NULL,NULL)
insert into city values(102,20,'Kalgoorlie-Boulder',0,1,null,'ADMIN',NULL,NULL)


--England


insert into city values(91,21,'London',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Birmingham',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Manchester',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Liverpool',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Newcastle',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Nottingham',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Sheffield',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Leeds',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Bristol',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Middlesbrough',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Leicester',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Portsmouth',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Bradford',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Bournemouth',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Reading',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Huddersfield',0,1,null,'ADMIN',NULL,NULL)	
insert into city values(91,21,'Stoke',0,1,null,'ADMIN',NULL,NULL)	
insert into city values(91,21,'Coventry',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Birkenhead',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Southampton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Hull	299724',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Sunderland',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Wigan',0,1,null,'ADMIN',NULL,NULL)	
insert into city values(91,21,'Brighton',0,1,null,'ADMIN',NULL,NULL)
insert into city values(91,21,'Southend',0,1,null,'ADMIN',NULL,NULL)

--HongKong

insert into city values(142,22,'Hong Kong',0,1,null,'ADMIN',NULL,NULL)


--Singapore

insert into city values(143,23,'Singapore',0,1,null,'ADMIN',NULL,NULL)