insert into  Country values('United States',1,null,'ADMIN',null,'ADMIN')
insert into  Country values('Canada',1,null,'ADMIN',null,'ADMIN')
insert into  Country values('Malaysia',1,null,'ADMIN',null,'ADMIN')
insert into  Country values('Swaziland',1,null,'ADMIN',null,'ADMIN')
insert into  Country values('Australia',1,null,'ADMIN',null,'ADMIN')
insert into  Country values('United Kingdom',1,null,'ADMIN',null,'ADMIN')
insert into  Country values('China',1,null,'ADMIN',null,'ADMIN')
insert into  Country values('Southeast Asian',1,null,'ADMIN',null,'ADMIN')


insert into  State values(16,'Alabama',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Alaska',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Arizona',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Arkansas',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'California',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Colorado',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Connecticut',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Delaware',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'District Of Columbia',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Florida',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Georgia',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Hawaii',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Idaho',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Illinois',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Indiana',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Iowa',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Kansas',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Kentucky',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Louisiana',1,null,'ADMIN',NULL,NULL)
--insert into  State values(16,'Maine',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Maryland',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Massachusetts',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Michigan',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Minnesota',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Mississippi',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Missouri',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Montana',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Nebraska',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Nevada',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'New Hampshire',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'New Jersey',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'New Mexico',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'New York',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'North Carolina',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'North Dakota',1,null,'ADMIN',NULL,NULL)
insert into  State values(16,'Ohio',1,null,'ADMIN',NULL,NULl)

insert into  State values(16,'Oklahoma',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Oregon',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Pennsylvania', 1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Rhode Island',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'South Carolina',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'South Dakota',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Tennessee',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Texas', 1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Utah',1,null,'ADMIN',NULL,NULl)
--insert into  State values(16,'Vermont',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Virginia',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Washington',1,null,'ADMIN',NULL,NULl)
--insert into  State values(16,'West Virginia',1,null,'ADMIN',NULL,NULl)
insert into  State values(16,'Wisconsin',1,null,'ADMIN',NULL,NULl)
--insert into  State values(16,'Wyoming',1,null,'ADMIN',NULL,NULl)


insert into  State values(17,'Alberta',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'British Columbia',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Manitoba',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'New Brunswick',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Newfoundland and Labrador',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Northwest Territories', 1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Nova Scotia',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Nunavut',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Ontario', 1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Prince Edward Island',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Quebec',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Saskatchewan',1,null,'ADMIN',NULL,NULl)
insert into  State values(17,'Yukon',1,null,'ADMIN',NULL,NULl)


insert into  State values(21,'England',1,null,'ADMIN',NULL,NULl)
insert into  State values(21, 'Northern Ireland',1,null,'ADMIN',NULL,NULl)
insert into  State values(21, 'Scotland', 1,null,'ADMIN',NULL,NULl)
insert into  State values(21, 'Wales', 1,null,'ADMIN',NULL,NULl)

insert into  State values(20, 'Australian Capital Territory',1,null,'ADMIN',NULL,NULl)
insert into  State values(20, 'New South Wales',1,null,'ADMIN',NULL,NULl)
insert into  State values(20, 'Northern Territory',1,null,'ADMIN',NULL,NULl)
insert into  State values(20, 'Queensland', 1,null,'ADMIN',NULL,NULl)
insert into  State values(20, 'South Australia',1,null,'ADMIN',NULL,NULl)
insert into  State values(20, 'Tasmania',1,null,'ADMIN',NULL,NULl)
insert into  State values(20, 'Victoria', 1,null,'ADMIN',NULL,NULl)
insert into  State values(20, 'Western Australia',  1,null,'ADMIN',NULL,NULl)

insert into  State values(19, 'Aargau',  1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Ausser-Rhoden',  1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Basel-Landschaft',  1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Bern', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Fribourg',  1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Geneve',  1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Glarus', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Graubunden', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Inner-Rhoden', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Luzern', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Neuchatel', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Nidwalden', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Obwalden', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Sankt Gallen', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Schaffhausen', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Solothurn', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Thurgau', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Ticino', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Uri', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Valais',  1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Vaud', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Zug', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Zurich', 1,null,'ADMIN',NULL,NULl)
insert into  State values(19, 'Jura',  1,null,'ADMIN',NULL,NULl)

insert into  State values(18, 'Johor', 1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Kedah',  1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Kelantan', 1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Melaka',  1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Negeri Sembilan',  1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Pahang', 1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Perak',  1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Pulau Pinang',  1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Sarawak',  1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Selangor', 1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Terengganu',  1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Kuala Lumpur', 1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Labuan', 1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Sabah',  1,null,'ADMIN',NULL,NULl)
insert into  State values(18, 'Putrajaya', 1,null,'ADMIN',NULL,NULl)


insert into  State values(22,'Hong Kong',1,null,'ADMIN',NULL,NULL)

insert into  State values(23,'Singapore',1,null,'ADMIN',NULL,NULL)